packages:
  - packages/*
  - docs
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@tailwindcss/oxide"
  - esbuild
catalog:
  "@starknet-io/types-js": "^0.7.10"
  tsdown: ^0.21.9
  typescript: ^5.9.3
  vitest: ^3.1.1
