name: Release

on:
  push:
    branches:
      - master
      - develop

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Setup npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" >> .npmrc

      - name: install dependencies
        run: pnpm install

      - name: run tests
        run: pnpm test

      - name: copy readme to every package
        run: echo "./packages/core/ ./packages/ui/" | xargs -n 1 cp README.md

      - name: Create Master Release
        if: github.ref == 'refs/heads/master'
        uses: changesets/action@v1
        with:
          version: pnpm run version
          commit: "chore: version bump"
          title: "Master branch version bump"
          publish: pnpm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Develop Release
        if: github.ref == 'refs/heads/develop'
        uses: changesets/action@v1
        with:
          version: pnpm run version
          commit: "chore: version bump"
          title: "Develop branch version bump"
          publish: pnpm run publish:next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
